// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5T-Q1Gkabddk3jBiBL_a0QbVKbVbuGSs',
    appId: '1:426907685755:web:b0c4ea6895e300872f63de',
    messagingSenderId: '426907685755',
    projectId: 'flutterchatapp-9d773',
    authDomain: 'flutterchatapp-9d773.firebaseapp.com',
    storageBucket: 'flutterchatapp-9d773.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB93ImYaoizEGavZSwtWZSvAGKbTII6jLY',
    appId: '1:426907685755:android:0750535425e9f77b2f63de',
    messagingSenderId: '426907685755',
    projectId: 'flutterchatapp-9d773',
    storageBucket: 'flutterchatapp-9d773.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4ia0kjIn1YFzoTkur97fbXazdC1gEDS8',
    appId: '1:426907685755:ios:7bc2c9586a8596e12f63de',
    messagingSenderId: '426907685755',
    projectId: 'flutterchatapp-9d773',
    storageBucket: 'flutterchatapp-9d773.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4ia0kjIn1YFzoTkur97fbXazdC1gEDS8',
    appId: '1:426907685755:ios:7bc2c9586a8596e12f63de',
    messagingSenderId: '426907685755',
    projectId: 'flutterchatapp-9d773',
    storageBucket: 'flutterchatapp-9d773.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5T-Q1Gkabddk3jBiBL_a0QbVKbVbuGSs',
    appId: '1:426907685755:web:479b7348a11c68192f63de',
    messagingSenderId: '426907685755',
    projectId: 'flutterchatapp-9d773',
    authDomain: 'flutterchatapp-9d773.firebaseapp.com',
    storageBucket: 'flutterchatapp-9d773.firebasestorage.app',
  );
}
